In [1]:
import quandl
import pandas as pd
import numpy as np
import datetime

from sklearn.linear_model import LinearRegression
from sklearn import preprocessing, cross_validation, svm

C:\Users\Vinayak\Anaconda3\lib\site-packages\sklearn\cross_validation.py:41: DeprecationWarning: This module was deprecated in version 0.18 in favor of the model_selection module into which all the refactored classes and functions are moved. Also note that the interface of the new CV iterators are different from that of this module. This module will be removed in 0.20.
  "This module will be removed in 0.20.", DeprecationWarning)


In [2]:
#df = quandl.get("WIKI/AMZN")

In [2]:
#df.to_csv(r'amazon.csv',index=True , header=True)
df=pd.read_csv("amazon.csv")

In [6]:
df.shape[0]

5248

In [5]:
#df1 = quandl.get("WIKI/FB")

In [7]:
#df1.to_csv(r'FB.csv',index=True , header=True)
df1=pd.read_csv("FB.CSV")

In [10]:
df1.shape[0]

1472

In [8]:
#df2 = quandl.get("WIKI/GOOGL")

In [11]:
#df2.to_csv(r'GOOGL.csv',index=True , header=True)
df2=pd.read_csv("GOOGL.csv")

In [15]:
df2.shape[0]

3424

In [11]:
df = df[['Adj. Close']]
df.index

RangeIndex(start=0, stop=5248, step=1)

In [12]:
img=df.plot(grid = True).axhline(y = 0, color = "black", lw = 2)

In [13]:
forecast_out = int(30) # predicting 30 days into future
df['Prediction'] = df[['Adj. Close']].shift(-forecast_out) #  label column with data shifted 30 units up

In [14]:
df.head()

Adj. Close  Prediction
0    1.729167    1.541667
1    1.708333    1.515833
2    1.635833    1.588333
3    1.427500    1.911667
4    1.395833    2.000000

In [15]:
X = np.array(df.drop(['Prediction'], 1))
X = preprocessing.scale(X)

In [16]:
X

array([[-0.70904095],
       [-0.70911489],
       [-0.7093722 ],
       ...,
       [ 4.59285269],
       [ 4.80686902],
       [ 4.59814099]])

In [17]:
X_forecast = X[-forecast_out:] # set X_forecast equal to last 30
X = X[:-forecast_out] # remove last 30 from X

In [18]:
X_forecast

array([[4.30519061],
       [4.43487812],
       [4.47288997],
       [4.42650202],
       [4.49627915],
       [4.54799089],
       [4.55452141],
       [4.60861111],
       [4.68651589],
       [4.65113044],
       [4.65279856],
       [4.58536389],
       [4.6094984 ],
       [4.69240755],
       [4.74220272],
       [4.76832478],
       [4.79267224],
       [4.88860693],
       [4.95781618],
       [4.92157893],
       [4.93158765],
       [4.90078066],
       [4.86301725],
       [4.76807634],
       [4.91565177],
       [4.89914803],
       [4.76513051],
       [4.59285269],
       [4.80686902],
       [4.59814099]])

In [19]:
y = np.array(df['Prediction'])
y = y[:-forecast_out]

In [20]:
y

array([1.54166667e+00, 1.51583333e+00, 1.58833333e+00, ...,
       1.49556000e+03, 1.55586000e+03, 1.49705000e+03])

In [21]:
X_train, X_test, y_train, y_test = cross_validation.train_test_split(X, y, test_size = 0.2)


In [22]:
clf = LinearRegression()
clf.fit(X_train,y_train)
# Testing
confidence = clf.score(X_test, y_test)
print("confidence: ", confidence)

confidence:  0.989057341444692


In [23]:
forecast_prediction = clf.predict(X_forecast)
print(forecast_prediction)

[1499.47488662 1538.29583707 1549.67439151 1535.78851788 1556.67576161
 1572.15527032 1574.11012934 1590.30146171 1613.62165499 1603.02929385
 1603.52863284 1583.34258855 1590.56706756 1615.38527781 1630.29107789
 1638.11051399 1645.3987384  1674.11604247 1694.83329846 1683.98595571
 1686.98198965 1677.76015468 1666.45596987 1638.03614435 1682.21170866
 1677.27143992 1637.15433295 1585.58430189 1649.64843194 1587.16731273]


In [24]:
df1 = df1[['Adj. Close']]
forecast_out = int(30) # predicting 30 days into future
df1['Prediction'] = df1[['Adj. Close']].shift(-forecast_out) #  label column with data shifted 30 units up
X = np.array(df1.drop(['Prediction'], 1))
X = preprocessing.scale(X)
X_forecast = X[-forecast_out:] # set X_forecast equal to last 30
X = X[:-forecast_out] # remove last 30 from X
y = np.array(df1['Prediction'])
y = y[:-forecast_out]

In [25]:
X_train, X_test, y_train, y_test = cross_validation.train_test_split(X, y, test_size = 0.2)


In [26]:
clf = LinearRegression()
clf.fit(X_train,y_train)
# Testing
confidence = clf.score(X_test, y_test)
print("confidence: ", confidence)

confidence:  0.9797537473709981


In [27]:
forecast_prediction1 = clf.predict(X_forecast)
print(forecast_prediction1)

[176.93689216 183.35723187 183.80070902 181.1801622  179.81949366
 181.73450864 182.82304348 187.15702476 188.80998506 185.31256296
 182.14774872 179.74894048 180.43431426 184.24418618 183.61928655
 187.58034386 186.19951727 189.11235585 188.63864161 185.73588206
 188.06413712 187.73152925 188.97124948 176.34222961 171.89737904
 173.14717829 168.61161649 163.06815206 163.74344682 155.81125317]


In [28]:
df2 = df2[['Adj. Close']]
forecast_out = int(30) # predicting 30 days into future
df2['Prediction'] = df2[['Adj. Close']].shift(-forecast_out) #  label column with data shifted 30 units up
X = np.array(df2.drop(['Prediction'], 1))
X = preprocessing.scale(X)
X_forecast = X[-forecast_out:] # set X_forecast equal to last 30
X = X[:-forecast_out] # remove last 30 from X
y = np.array(df2['Prediction'])
y = y[:-forecast_out]

In [29]:
X_train, X_test, y_train, y_test = cross_validation.train_test_split(X, y, test_size = 0.2)


In [30]:
clf = LinearRegression()
clf.fit(X_train,y_train)
# Testing
confidence = clf.score(X_test, y_test)
print("confidence: ", confidence)

confidence:  0.9790896298724954


In [31]:
forecast_prediction2 = clf.predict(X_forecast)
print(forecast_prediction2)

[1073.01187707 1091.86382732 1110.81735058 1115.02247311 1123.23972944
 1133.55954704 1129.64898623 1148.12511636 1163.98066288 1137.37869213
 1123.57492037 1090.55353552 1103.48377942 1114.27083285 1120.50741553
 1134.86983884 1149.43540816 1181.39027642 1186.56034252 1160.13104588
 1169.25230199 1170.99935772 1154.55468775 1119.66435956 1115.32719213
 1113.49887799 1072.00630429 1044.98788421 1072.96109057 1025.06941737]


In [32]:
def pred(s,a,f,g):
    output1=''
    output7=''
    output30=''
    day=1
    count=0
    if a==1:
        fp=forecast_prediction
    elif f==1:
        fp=forecast_prediction1
    elif g==1:
        fp=forecast_prediction2
    for i in fp:
        i=str(i)
        if day==1:
                output1=output1+"\n"+"Day"+str(day)+"--"+i+"\n"
        if day<8:
                output7=output7+"\n"+"Day"+str(day)+"--"+i+"\n"
        if day<31:
                output30=output30+"\t"+"Day"+str(day)+"--"+i+"\t"
                count=count+1
                if count==6:
                    output30=output30+"\n"
                    count=0
        day=day+1
    if s==1:
        return output1
    elif s==7:
        return output7
    elif s==30:
        return output30

In [51]:
from tkinter import *
import tkinter.messagebox
from PIL import ImageTk,Image 

In [52]:
# top = tkinter.Tk()
# # Code to add widgets will go here...
# def helloCallBack():
#     tkinter.messagebox.showinfo( "Hello Python", output)

# topFrame= Frame(top)
# bottomframe = Frame(top)


# B = tkinter.Button(topFrame, text ="Hello", command = helloCallBack)
# B1=tkinter.Button(topFrame, text ="Hi", command = helloCallBack)
# one= Label(top, text='Label', fg="red",bg="black")
# one.pack(fill=X)
# topFrame.pack()
# bottomframe.pack(side=BOTTOM)
# B1.pack(side=LEFT)
# B.pack(side=RIGHT,fill=Y)
# top.mainloop()

In [84]:
root = Tk() 
root.title("Stock predictor")
root.geometry('600x600')

''

In [85]:
canvas = Canvas(root, width = 300, height = 300)  
canvas.pack()       
#img = PhotoImage(file="/home/vineet/SL/SLProject/amzn.png")      
img = ImageTk.PhotoImage(Image.open("tree.png"))  
canvas.create_image(20, 20, anchor=NW, image=img)
lbl=Label(root,text="Predict Stocks for : ").place(x=80,y=300)


In [86]:
def clicked1():
    window2=Tk()
    window2.geometry('300x300')
    lbl=Label(window2,text="Prediction for 1 - day :-"+pred(1,var1.get(),var2.get(),var3.get())).place(x=50,y=50)
    window2.mainloop()

In [87]:
def clicked7():
    window2=Tk()
    window2.geometry('300x300')
    lbl=Label(window2,text="Prediction for 1 - week :-"+pred(7,var1.get(),var2.get(),var3.get())).place(x=50,y=50)
    window2.mainloop()

In [88]:
def clicked30():
    window2=Tk()
    window2.geometry('1500x300')
    lbl=Label(window2,text="Prediction for 1 - month :-"+pred(30,var1.get(),var2.get(),var3.get())).place(x=50,y=50)
    window2.mainloop()

In [89]:
def AmznGraph():
    window2=tkinter.Toplevel()
    window2.geometry('650x650')
    lbl=Label(window2,text="Amazon Graph").place(x=300,y=300)
    canvas = Canvas(window2, width = 600, height = 600)
    canvas.pack()
    img1 = ImageTk.PhotoImage(Image.open("AmznGraph.png"))  
    canvas.create_image(20, 20, anchor=NW, image=img1)
    window2.mainloop()

In [90]:
def GoogleGraph():
    window2=tkinter.Toplevel()
    window2.geometry('650x650')
    lbl=Label(window2,text="Google Graph").place(x=300,y=300)
    canvas = Canvas(window2, width = 600, height = 600)
    canvas.pack()
    img1 = ImageTk.PhotoImage(Image.open("GoogleGraph.png"))  
    canvas.create_image(20, 20, anchor=NW, image=img1)
    window2.mainloop()

In [91]:
def FbGraph():
    window2=tkinter.Toplevel()
    window2.geometry('650x650')
    lbl=Label(window2,text="FB graph").place(x=300,y=300)
    canvas = Canvas(window2, width = 600, height = 600)
    canvas.pack()
    img1 = ImageTk.PhotoImage(Image.open("FbGraph.png"))  
    canvas.create_image(20, 20, anchor=NW, image=img1)
    window2.mainloop()

In [92]:

def CompGraph():
    window2=tkinter.Toplevel()
    window2.geometry('650x650')
    lbl=Label(window2,text="Stock Graph").place(x=300,y=300)
    canvas = Canvas(window2, width = 600, height = 600)
    canvas.pack()
    img1 = ImageTk.PhotoImage(Image.open("stock.png"))  
    canvas.create_image(20, 20, anchor=NW, image=img1)
    window2.mainloop()

In [93]:
var1= IntVar()
var2= IntVar()
var3= IntVar()
btn1 = Button(root, text="1-Day", command=clicked1).place(x=30,y=320)
btn2 = Button(root, text="1-Week", command=clicked7).place(x=150,y=320)
btn3 = Button(root, text="1-Month", command=clicked30).place(x=270,y=320)
btn4 = Button(root, text="Amazon graph", command=AmznGraph).place(x=30,y=420)
btn5 = Button(root, text="Google graph", command=GoogleGraph).place(x=150,y=420)
btn6 = Button(root, text="Facebook graph", command=FbGraph).place(x=270,y=420)
chk1 = Checkbutton(root, text="Amazon", variable=var1).place(x=30,y=380)
chk2 = Checkbutton(root, text="Facebook", variable=var2).place(x=150,y=380)
chk3 = Checkbutton(root, text="Google", variable=var3).place(x=270,y=380)
btn7 = Button(root, text="Comparision between the 3 companies", command=CompGraph).place(x=100,y=450)
#btn.grid(column=1, row=0)
 
root.mainloop()